### ISSUE TITLE
stupid pyaudio acts stupid on pi

### ISSUE THREAD

**Issue by skittlemittle** [afshaan4/loudsounds#3]
crashes randomly after running **JUST FINE** for some time
runs for like 5 minutes or a solid 20 minutes then just dies:
```
Traceback (most recent call last):
  File "./loud.py", line 188, in <module>
    lt.listen()
  File "./loud.py", line 167, in listen
    self.sound_detected()
  File "./loud.py", line 139, in sound_detected
    self.record(args.record_length)
  File "./loud.py", line 131, in record
    audio = self.stream.read(INPUT_FRAMES_PER_BLOCK)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed
```

maybe set a hard limit to `INPUT_FRAMES_PER_BLOCK`? 

this only happens on the pi, is it coz the pi is 32 bit? is it coz pyaudio for the pi is messed up? i dunno

**Comment by skittlemittle** [comment]
also crashes like so:
```
(5093) Error recording: [Errno -9988] Stream closed
(5094) Error recording: [Errno -9988] Stream closed
^CTraceback (most recent call last):
  File "./loud.py", line 155, in listen
    block = self.stream.read(INPUT_FRAMES_PER_BLOCK)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9988] Stream closed
```

**Comment by skittlemittle** [comment]
this seems to have made it more stable:
``` python
audio = self.stream.read(FRAMES_PER_BLOCK, False)
```
Iv'e yet to test it overnight though so we might still have issues.

**Comment by skittlemittle** [comment]
FINALLY FIXED HAHAHAHAHAHAHAHA
